version: "3.8"

services:
  wren-engine:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./etc/mdl:/app/etc/mdl
    environment:
      - WREN_PORT=8080
      - WREN_DATASOURCE_TYPE=duckdb
